# Generated by Django 5.2.7 on 2025-11-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='ServiceAllowedTime',
        ),
    ]
