# Generated by Django 5.2.7 on 2025-11-26 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_reservation_address_reservation_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound (Sent)'), ('INBOUND', 'Inbound (Received)')], max_length=10)),
                ('message_type', models.CharField(choices=[('TEMPLATE', 'Template'), ('TEXT', 'Text'), ('INTERACTIVE', 'Interactive (Button/List)'), ('UNKNOWN', 'Unknown')], default='TEXT', max_length=20)),
                ('whatsapp_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=32)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('RECEIVED', 'Received')], default='SENT', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(blank=True, help_text='Related reservation if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='agenda.reservation')),
            ],
            options={
                'verbose_name': 'WhatsApp Log',
                'verbose_name_plural': 'WhatsApp Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
