# Generated by Django 5.2.7 on 2025-11-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32, unique=True)),
                ('state', models.CharField(default='MENU', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
