# Generated by Django 5.2.7 on 2025-11-23 23:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('active', models.BooleanField(default=True)),
                ('accepts_reservations', models.BooleanField(default=True)),
                ('calendar_color', models.CharField(default='#3b82f6', max_length=7)),
                ('bio', models.TextField(blank=True, default='', max_length=600)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='professionals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='AdminAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('CANCEL', 'Cancel')], max_length=16)),
                ('model_name', models.CharField(max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('admin_user', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('PENDING', 'Pending')], db_index=True, default='RESERVED', max_length=16)),
                ('cancelled_by', models.CharField(blank=True, choices=[('admin', 'Admin'), ('client', 'Client')], max_length=32, null=True)),
                ('total_min', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_duration_min', models.PositiveIntegerField()),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.professional')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='agenda.reservation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.service')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_exceptions', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='agenda.professional')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BLOCKED', 'Blocked'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=12)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='agenda.professional')),
            ],
            options={
                'ordering': ['start'],
                'unique_together': {('professional', 'start')},
            },
        ),
        migrations.CreateModel(
            name='ReservationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.professional')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_slots', to='agenda.reservation')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='agenda.slot')),
            ],
        ),
        migrations.CreateModel(
            name='SlotBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField()),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_slot_blocks', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_blocks', to='agenda.professional')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, default='')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='agenda.reservation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='agenda.professional')),
            ],
            options={
                'ordering': ['professional__first_name', 'professional__last_name', 'weekday'],
                'unique_together': {('professional', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='agenda.workschedule')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_override_min', models.PositiveIntegerField(blank=True, help_text='Optional: overrides default service duration.', null=True)),
                ('active', models.BooleanField(default=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='agenda.professional')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='catalog.service')),
            ],
            options={
                'ordering': ['professional__first_name', 'professional__last_name', 'service__name'],
                'unique_together': {('professional', 'service')},
            },
        ),
    ]
