# Generated by Django 5.2.7 on 2025-11-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_reservation_address_reservation_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
