# Generated by Django 5.2.7 on 2025-11-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_professional_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmation_token',
            field=models.UUIDField(blank=True, default=None, help_text='Unique token for WhatsApp confirmation link', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration time for confirmation token (2 hours from generation)', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('PENDING', 'Pending'), ('RECONFIRMED', 'Re-Confirmed by Client')], db_index=True, default='RESERVED', max_length=16),
        ),
    ]
