# Generated by Django 5.2.7 on 2025-12-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_reservation_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('PENDING', 'Pending'), ('WAITING_CLIENT', 'Waiting for Client Confirmation'), ('RECONFIRMED', 'Re-Confirmed by Client')], db_index=True, default='RESERVED', max_length=16),
        ),
    ]
