# Generated by Django 5.2.7 on 2025-12-03 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_reservation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reservada (Sistema)'), ('CONFIRMED', 'Confirmada'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada'), ('NO_SHOW', 'No Show (No asistió)'), ('PENDING', 'Pendiente (Esperando Aprobación)'), ('WAITING_CLIENT', 'Esperando Confirmación Cliente'), ('RECONFIRMED', 'Confirmada (Por Cliente)')], db_index=True, default='RESERVED', max_length=16),
        ),
    ]
