# Generated by Django 5.2.7 on 2025-10-22 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('es_hoja', models.BooleanField(default=False)),
                ('accion', models.CharField(blank=True, default='', max_length=120)),
                ('arbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos', to='chatbot.arbol')),
                ('derecha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodo_derecha', to='chatbot.nodo')),
                ('izquierda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodo_izquierda', to='chatbot.nodo')),
            ],
        ),
        migrations.CreateModel(
            name='SesionChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.CharField(blank=True, default='', max_length=120)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('arbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.arbol')),
                ('nodo_actual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.nodo')),
            ],
        ),
    ]
