# Generated by Django 5.2.7 on 2025-11-20 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodo',
            name='arbol',
        ),
        migrations.RemoveField(
            model_name='sesionchat',
            name='arbol',
        ),
        migrations.RemoveField(
            model_name='nodo',
            name='derecha',
        ),
        migrations.RemoveField(
            model_name='nodo',
            name='izquierda',
        ),
        migrations.RemoveField(
            model_name='sesionchat',
            name='nodo_actual',
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('state', models.CharField(default='start', max_length=120)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Arbol',
        ),
        migrations.DeleteModel(
            name='Nodo',
        ),
        migrations.DeleteModel(
            name='SesionChat',
        ),
    ]
