# Generated by Django 5.2.7 on 2025-10-22 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('contenido', models.TextField()),
                ('canal', models.CharField(default='whatsapp', max_length=32)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramacionRecordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField()),
                ('enviado', models.BooleanField(default=False)),
                ('canal', models.CharField(default='whatsapp', max_length=32)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='agenda.reserva')),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='LogEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('exito', models.BooleanField(default=False)),
                ('respuesta', models.TextField(blank=True, default='')),
                ('recordatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notificaciones.programacionrecordatorio')),
            ],
            options={
                'ordering': ['-fecha_intento'],
            },
        ),
    ]
