# Generated by Django 5.2.7 on 2025-10-22 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=32, null=True)),
                ('acepta_reservas', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('color_calendario', models.CharField(default='#3b82f6', max_length=7)),
                ('biografia', models.TextField(blank=True, default='', max_length=600)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profesionales/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Descanso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descansos', to='profesionales.calendariolaboral')),
            ],
        ),
        migrations.AddField(
            model_name='calendariolaboral',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios', to='profesionales.profesional'),
        ),
        migrations.AlterUniqueTogether(
            name='calendariolaboral',
            unique_together={('profesional', 'dia_semana')},
        ),
    ]
