# Generated by Django 5.2.7 on 2025-11-01 20:00
# -*- coding: utf-8 -*-
from django.db import migrations

def create_initial_profesionales_and_asignaciones(apps, schema_editor):
    """
    Crea los profesionales iniciales y los asigna a todos los servicios existentes.
    """
    Profesional = apps.get_model('profesionales', 'Profesional')
    Servicio = apps.get_model('catalogo', 'Servicio')
    ProfesionalServicio = apps.get_model('catalogo', 'ProfesionalServicio')

    # --- 1. Crear Profesionales ---
    # (Puedes añadir más o modificar los datos aquí)
    profesionales_data = [
        {
            "nombre": "Felipe Cuevas",
            "email": "felipe@revitek.cl",
            "telefono": "911111111",
            "acepta_reservas": True,
            "activo": True,
            "color_calendario": "#3b82f6" # Azul
        },
        {
            "nombre": "Isaac Salomón",
            "email": "isaac@revitek.cl",
            "telefono": "922222222",
            "acepta_reservas": True,
            "activo": True,
            "color_calendario": "#10b981" # Verde
        }
    ]

    profesionales_creados = []
    for data in profesionales_data:
        # get_or_create evita duplicados si se corre la migración de nuevo
        prof, created = Profesional.objects.get_or_create(
            email=data["email"],
            defaults=data
        )
        profesionales_creados.append(prof)
        if created:
            print(f"Profesional creado: {prof.nombre}")

    # --- 2. Asignar Servicios ---
    # Asigna TODOS los servicios a CADA profesional creado.
    try:
        # Obtenemos todos los servicios que ya fueron creados por 
        # la migración de 'catalogo' (0003_add_initial_services.py)
        servicios_a_asignar = Servicio.objects.filter(activo=True)
        
        if not servicios_a_asignar.exists():
            print("Advertencia: No se encontraron servicios para asignar. Asegúrate que la migración 'catalogo.0003' se haya ejecutado.")
            return

        for prof in profesionales_creados:
            for serv in servicios_a_asignar:
                # get_or_create previene errores si la asignación ya existe
                ProfesionalServicio.objects.get_or_create(
                    profesional=prof,
                    servicio=serv
                )
            print(f"Servicios asignados a {prof.nombre}")

    except Exception as e:
        # Si la tabla Servicio no existe aún (por orden de migración),
        # esta dependencia lo previene, pero es bueno ser defensivo.
        print(f"Error asignando servicios (puede que la migración de servicios no se haya ejecutado): {e}")


def delete_initial_profesionales(apps, schema_editor):
    """
    Elimina los profesionales creados si se revierte la migración.
    Las asignaciones (ProfesionalServicio) se borran en cascada.
    """
    Profesional = apps.get_model('profesionales', 'Profesional')
    emails_a_borrar = ['felipe@revitek.cl', 'isaac@revitek.cl']
    Profesional.objects.filter(email__in=emails_a_borrar).delete()
    print(f"Profesionales iniciales eliminados.")


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
        # --- ¡IMPORTANTE! ---
        # Esta migración DEPENDE de que los servicios ya estén creados
        # por la migración 0003 de la app 'catalogo'.
        ('catalogo', '0003_add_initial_services'),
    ]

    operations = [
        # Ejecuta nuestra función de Python
        migrations.RunPython(create_initial_profesionales_and_asignaciones, delete_initial_profesionales),
    ]