# Generated by Django 5.2.7 on 2025-10-22 03:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('profesionales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('CANCEL', 'Cancel')], max_length=16)),
                ('model_name', models.CharField(max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('admin_user', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('CONFIRMADO', 'Confirmado'), ('ASISTE', 'Asiste'), ('NO_ASISTIO', 'No Asistió'), ('PENDIENTE', 'Pendiente'), ('EN_ESPERA', 'En Espera'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], db_index=True, default='RESERVADO', max_length=16)),
                ('cancelled_by', models.CharField(blank=True, choices=[('admin', 'Admin'), ('client', 'Client')], max_length=32, null=True)),
                ('total_min', models.PositiveIntegerField(default=0)),
                ('nota', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota', models.TextField(blank=True, default='')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='agenda.reserva')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_min_eff', models.PositiveIntegerField()),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profesionales.profesional')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='agenda.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('inicio', models.DateTimeField(db_index=True)),
                ('fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'DISPONIBLE'), ('BLOQUEADO', 'BLOQUEADO'), ('RESERVADO', 'RESERVADO')], default='DISPONIBLE', max_length=12)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='profesionales.profesional')),
            ],
            options={
                'ordering': ['inicio'],
                'unique_together': {('profesional', 'inicio')},
            },
        ),
        migrations.CreateModel(
            name='ReservaSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profesionales.profesional')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaslot', to='agenda.reserva')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ocupacion', to='agenda.slot')),
            ],
        ),
    ]
