# Generated by Django 5.2.5 on 2025-10-04 02:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('profesionales', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular_nombre', models.CharField(blank=True, default='', max_length=120)),
                ('titular_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('titular_tel', models.CharField(blank=True, default='', max_length=32)),
                ('estado', models.CharField(choices=[('RESERVADO', 'RESERVADO'), ('CONFIRMADO', 'CONFIRMADO'), ('ASISTE', 'ASISTE'), ('NO_ASISTIO', 'NO_ASISTIO'), ('PENDIENTE', 'PENDIENTE'), ('EN_ESPERA', 'EN_ESPERA'), ('EN_PROGRESO', 'EN_PROGRESO'), ('COMPLETADO', 'COMPLETADO'), ('CANCELADO', 'CANCELADO')], db_index=True, default='RESERVADO', max_length=16)),
                ('total_min', models.PositiveIntegerField(default=0)),
                ('nota', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cliente')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota', models.TextField(blank=True, default='')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='agenda.reserva')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_min_eff', models.PositiveIntegerField()),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profesionales.profesional')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='agenda.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('inicio', models.DateTimeField(db_index=True)),
                ('fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'DISPONIBLE'), ('BLOQUEADO', 'BLOQUEADO'), ('RESERVADO', 'RESERVADO')], default='DISPONIBLE', max_length=12)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='profesionales.profesional')),
            ],
            options={
                'ordering': ['inicio'],
                'unique_together': {('profesional', 'inicio')},
            },
        ),
        migrations.CreateModel(
            name='ReservaSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profesionales.profesional')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaslot', to='agenda.reserva')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ocupacion', to='agenda.slot')),
            ],
        ),
    ]
