# Generated by Django 5.2.7 on 2025-10-21 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('CANCEL', 'Cancel')], max_length=16)),
                ('model_name', models.CharField(max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('CONFIRMADO', 'Confirmado'), ('ASISTE', 'Asiste'), ('NO_ASISTIO', 'No Asistió'), ('PENDIENTE', 'Pendiente'), ('EN_ESPERA', 'En Espera'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], db_index=True, default='RESERVADO', max_length=16)),
                ('cancelled_by', models.CharField(blank=True, choices=[('admin', 'Admin'), ('client', 'Client')], max_length=32, null=True)),
                ('total_min', models.PositiveIntegerField(default=0)),
                ('nota', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_min_eff', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservaSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('inicio', models.DateTimeField(db_index=True)),
                ('fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'DISPONIBLE'), ('BLOQUEADO', 'BLOQUEADO'), ('RESERVADO', 'RESERVADO')], default='DISPONIBLE', max_length=12)),
            ],
            options={
                'ordering': ['inicio'],
            },
        ),
    ]
