# Generated by Django 5.2.7 on 2025-10-21 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('catalogo', '0001_initial'),
        ('profesionales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaudit',
            name='admin_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialestado',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='agenda.reserva'),
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profesionales.profesional'),
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='agenda.reserva'),
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.servicio'),
        ),
        migrations.AddField(
            model_name='reservaslot',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profesionales.profesional'),
        ),
        migrations.AddField(
            model_name='reservaslot',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaslot', to='agenda.reserva'),
        ),
        migrations.AddField(
            model_name='slot',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='profesionales.profesional'),
        ),
        migrations.AddField(
            model_name='reservaslot',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ocupacion', to='agenda.slot'),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('profesional', 'inicio')},
        ),
    ]
